const BASE_URL = "/api/v1/";

module.exports = {
  BASE_URL: BASE_URL,
  api(name) {
    return `${BASE_URL}${name}`;
  },
  ERRORS: {
    WRONG_CREDENTIALS: "WRONG_CREDENTIALS",
    DB_INSERTION_FAILED: "DB_INSERTION_FAILED",
    USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
    PASSWORDS_NOT_SAME: "PASSWORDS_NOT_SAME",
    NO_USER_TO_BE_INVITED: "NO_USER_TO_BE_INVITED",
    NO_USER_TO_FOLLOW: "NO_USER_TO_FOLLOW",
    PERMISSION_DENIED: "PERMISSION_DENIED",
  },
};
